### ISSUE TITLE
Suggestion: Add support for iobroker

### ISSUE THREAD

**Issue by mikkel75** [weetmuts/wmbusmeters#14]
Hi,

This is a great tool - but wouldn't it be even greater if it was possible to integrate into iobroker?
I know there is a wmbus plugin for iobroker, but that is old and not supported anymore...I would so much love to see this great tool as an adapter in iobroker ;)

Any thoughts?

/M

**Comment by weetmuts** [comment]
Sounds fun! 

What is the best way for a device like wmbusmeters to integrate with iobroker?

Should wmbusmeters broadcast something so that wmbusmeters can be detected by iobroker
and then be autoconfigered from the iobroker side?

Or should wmbusmeters listen for iobroker signals, and then automatically register with iobroker
when it hears that there is an iobroker on the network?

Or should you simply supply an iobroker REST endpoint to wmbusmeters on the command line?

**Comment by BIBOLV** [comment]
Hi,
Try following:
1. Install MQTT Broker/Client adapter
2. Configure and start MQTT adapter
3. Add to /etc/wmbusmeters.conf 
`shell=/usr/bin/mosquitto_pub -h localhost -t wmbusmeters/$METER_ID -m "$METER_TOTAL_M3"`
4. When wmbusmeters sends data, check under Objects -> mqtt.0/wmbusmeters/[meter_id] and you should see value reported

**Comment by weetmuts** [comment]
@mikkel75 did you manage to integrate with iobroker?

**Comment by weetmuts** [comment]
The howto is added to the wiki. Closing this for now.
