### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by Horndrup** [weetmuts/wmbusmeters#30]
What is the best way to install updates?

**Comment by weetmuts** [comment]
Running "sudo make install" should be safe. The only thing it should overwrite are the binaries and the manual page.

It will print "... something ...  unchanged" for the other configuration files.

It does not currently detect that it has to upgrade any important configuration file.

I suppose it should! :-) Aka room for improvement.

But you can manually compare the file that would have been installed (is visible inside the install.sh script) with the file already installed. 

Or you could just remote wmbusmeters.service and 99-wmbus-usb-serial.rules
and redo the install. Since these are the only ones that might have changed.
Though it was some time ago since they changed.

**Comment by weetmuts** [comment]
Did you solve the upgrade? Can I close this issue now?

**Comment by Horndrup** [comment]
Yes I solved it. Sorry for my late feedback.
