### ISSUE TITLE
N-mode meter 169MHz  ARROW Wan MVM 169

### ISSUE THREAD

**Issue by bend94** [weetmuts/wmbusmeters#341]
Hi,

I would like to know if the wmbusmeters is able to read and decode -> Radio Module wM-Bus 169 Mhz
My counter is a ARROW Wan MVM 169

Best Regards

**Comment by weetmuts** [comment]
Please join the discussion here: https://github.com/xaelsouth/rtl-wmbus/issues/26
Be ready to collect signal samples so that rtl_433 and rtl_wmbus can add support for N mode.
:-)

**Comment by weetmuts** [comment]
The iM170A chip apparently supports N mode reception (169.40652 MHz to 169.43750 MHz)

I do not know if one can buy such a prepared USB dongle though or if there is some other
purchaseable/buildable board with an im170a chip. I supposed the antenna size needs to 
be different from the one in the im871a USB dongle (868.95MHz)

If you find one, then I can add support to wmbusmeters to configure N mode
relatively easy since wmbusmeters already can detect if you have plugged in an im871a or an im170a chip.

**Comment by weetmuts** [comment]
Then after we have received a telegram from the meter, the question is what protocol it uses. 
After reading the spec: https://www.maddalena.it/en/products/communication-modules/arrow-wan-169/83

I cannot conclusively say if the protocol is fully wmbus compliant, so we shall see if it is trivial to decode
(when it is compliant) or anything from messy, tricky or impossible....

But hopefully it is using the wmbus standard in a mostly compliant way.

**Comment by bend94** [comment]
Hi
i won't be available until next January, my house is under construction
we can keep in touch then

Best regards

**Comment by merbanan** [comment]
@bend94 are you near your meter now? You need a rtl-sdr to receive this signal.

**Comment by bend94** [comment]
Hi
I will be in my new house around April.
I will be able to catch some logs about my water counter in April for you
with pleasure.
Let s keep in touch, I am very interested to decode my water consumption
Best regards


Le dim. 6 févr. 2022 à 21:56, Benjamin Larsson ***@***.***> a
écrit :

**Comment by bend94** [comment]
Hi

My home will be ready at the end of April
Are you still interested in capturing  433Mhz frames ?
Let me know

thanks

**Comment by DarKOrange75** [comment]
Hi all, I also have this meter, anyone made progress on reading telegrams ?
