### ISSUE TITLE
Driver for OMS

### ISSUE THREAD

**Issue by GrzegorzOrlicki** [weetmuts/wmbusmeters#347]
Do you have universal driver for meters made for OMS standard? I would like to check if my device sends data compatibile with OMS standard of WM-Bus

**Comment by weetmuts** [comment]
Sort of, wmbusmeters always parses all of the OMS-data, if it can. Try just any driver:
wmbusmeters --debug 2744........hex..... MyMeter supercom587 12345678 NO_KEY
to see what it says.

I am working on an improved OMS protocol parser, the current one has its limitations.
But please post the meter telegram here! So that we can learn from it!
