### ISSUE TITLE
Problem with CUL

### ISSUE THREAD

**Issue by SWAT9119** [weetmuts/wmbusmeters#461]
Hello,

I have following CUL:

https://www.ebay.de/itm/372228009485

When I try to get some Messages from a WaterStar M meter, I get follow log:

[2022-02-01_17:34:24] Started auto cul on /dev/ttyUSB0 listening on t1
[2022-02-01_17:34:29] (cul) setting link mode(s) t1 is not supported for this cul device!
(wmbusmeters) logging started 2022-02-01 17:34:31 using 1.6.0-2-g1ba5660

What can I do?

Thank you in advance!

**Comment by SWAT9119** [comment]
Edit:

I have flashed the actual firmware like this: https://weetmuts.github.io/wmbusmeterswiki/nanoCUL.html

I got c1 telegrams, but not t1 telegrams

**Comment by geektoor** [comment]
Do you still get an error with the firmware like stated above? (not supported) or does it "work" but you don't see any telegrams? Because that might be a difference.
I use an cul myself (its an older one, v3, from busware i was using prior with homematic) and it flashed the mbus version published here: https://github.com/smarthomeagentur/culfw1/releases/ - needed the dfu-programmer to actually flash it, but at least i can see telegrams and all modes seem to work (i have only c1 meters, but at least t1 didn't give me an error).

**Comment by SWAT9119** [comment]
I´ve sold this problem - Thank you!

**Comment by geektoor** [comment]
Glad to hear, buuuut: could you explain how? others might run into such issues and find this issue, and then just see "its solved" but not "how" ;) Or did you really "sold" the problem? :D

And don't be afraid if you just made a mistake, even sharing mistakes helps other people as well. We all learn from our mistakes, not our success :)

**Comment by SWAT9119** [comment]
I only looked at the watermeters manufacters paper and expectet t1-telegrams, but the watermeter sent it with c1 so I couldnt get any telegrams
